name: pylana-dev
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - alabaster=0.7.12
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - babel=2.8.0
  - blas=1.0
  - bleach=3.1.5
  - ca-certificates=2020.4.5.2
  - certifi=2020.4.5.2
  - cffi=1.14.0
  - chardet=3.0.4
  - cmarkgfm=0.4.2
  - cryptography=2.8
  - docutils=0.16
  - entrypoints=0.3
  - future=0.18.2
  - idna=2.9
  - imagesize=1.2.0
  - intel-openmp=2019.4
  - jinja2=2.11.1
  - keyring=21.2.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - markupsafe=1.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - packaging=20.3
  - pandas=1.0.3
  - pip=20.0.2
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - py=1.8.1
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.8.1
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2019.3
  - readline=7.0
  - readme_renderer=24.0
  - requests=2.23.0
  - requests-toolbelt=0.9.1
  - setuptools=46.1.1
  - six=1.14.0
  - snowballstemmer=2.0.0
  - sphinx=2.4.0
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.31.1
  - tk=8.6.8
  - tqdm=4.46.1
  - twine=3.1.1
  - urllib3=1.25.8
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
