name: PyLana Unit Tests

on:
  push: {branches: enhancement}

jobs:
  setup-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up conda environment
      run: sudo $CONDA/bin/conda env update --file environment-dev.yaml --name base

    - name: Set up credentials
      run: |
        echo "{\"scheme\": \"https\",\"host\": \"cloud-backend.lanalabs.com\",\"port\": \"\",\"token\": \"${{ secrets.PYLANA_TEST_TOKEN }}\"}" > tests/config.json
        echo "{\"scheme\": \"https\",\"host\": \"cloud-backend.lanalabs.com\",\"port\": \"\",\"token\": \"${{ secrets.PYLANA_TEST_TOKEN }}\"}" > tests/config_useradmin.json

    - name: Test with pytest
      run: sudo $CONDA/bin/pytest